import '@/styles/globals.css';

import { fontPoppins } from '@/lib/fonts';
import { cn } from '@/lib/utils';

import { Providers } from '@/providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body
        className={cn(
          'min-h-screen bg-white font-sans antialiased',
          fontPoppins.className
        )}
        suppressHydrationWarning={true}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
